version: 0.2

phases:
  install:
    commands:
      - echo Installing Python dependencies...
      - pip install -r requirements.txt 
  build:
    commands:
      - echo No build step required for this Python app.  
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - '**/*'  
